import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { SchedulerGeneratedModule, SchedulerGeneratedSharedModule } from './generated/module.js';
import { SchedulerValidator, registerValidationChecks } from './scheduler-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SchedulerAddedServices = {
    validation: {
        SchedulerValidator: SchedulerValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SchedulerServices = LangiumServices & SchedulerAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SchedulerModule: Module<SchedulerServices, PartialLangiumServices & SchedulerAddedServices> = {
    validation: {
        SchedulerValidator: () => new SchedulerValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSchedulerServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Scheduler: SchedulerServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SchedulerGeneratedSharedModule
    );
    const Scheduler = inject(
        createDefaultModule({ shared }),
        SchedulerGeneratedModule,
        SchedulerModule
    );
    shared.ServiceRegistry.register(Scheduler);
    registerValidationChecks(Scheduler);
    return { shared, Scheduler };
}
