import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { TodoListGeneratedModule, TodoListGeneratedSharedModule } from './generated/module.js';
import { TodoListValidator, registerValidationChecks } from './todo-list-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type TodoListAddedServices = {
    validation: {
        TodoListValidator: TodoListValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type TodoListServices = LangiumServices & TodoListAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const TodoListModule: Module<TodoListServices, PartialLangiumServices & TodoListAddedServices> = {
    validation: {
        TodoListValidator: () => new TodoListValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createTodoListServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    TodoList: TodoListServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        TodoListGeneratedSharedModule
    );
    const TodoList = inject(
        createDefaultModule({ shared }),
        TodoListGeneratedModule,
        TodoListModule
    );
    shared.ServiceRegistry.register(TodoList);
    registerValidationChecks(TodoList);
    return { shared, TodoList };
}
